//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pregunta2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class deducciones
    {
        public int codigo_deduccion { get; set; }
        public int id_empleado { get; set; }
        public Nullable<decimal> cooperativa { get; set; }
        public Nullable<decimal> prestamo { get; set; }
        public Nullable<decimal> ahorro { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
